IF OBJECT_ID (N'[S_View_TicketsConSLA_Top10Usuario]', N'P') IS NOT NULL
	DROP PROCEDURE [S_View_TicketsConSLA_Top10Usuario]
GO
CREATE PROCEDURE [S_View_TicketsConSLA_Top10Usuario]
	@TIPO NVARCHAR(510),
	@GRUPO NVARCHAR(510),
	@AREA NVARCHAR(510),
	@ANIO INT,
	@MES INT
AS
BEGIN
	SET NOCOUNT ON
	SET DATEFORMAT DMY

	SELECT	TOP 10 UPPER(LTRIM(RTRIM(USUARIO))) AS USUARIO,
			COUNT(TICKET) AS CANTIDAD
	FROM VIEW_TICKETSCONSLA WITH(NOLOCK)
	WHERE
		[TIPO] = CASE WHEN LEN(LTRIM(RTRIM(@TIPO)))=0 THEN [TIPO] ELSE @TIPO END AND
		[GRUPO] = CASE WHEN LEN(LTRIM(RTRIM(@GRUPO)))=0 THEN [GRUPO] ELSE @GRUPO END AND
		ISNULL([ÁREA DE USUARIO],'') = CASE WHEN LEN(LTRIM(RTRIM(@AREA)))=0 THEN ISNULL([ÁREA DE USUARIO],'') ELSE @AREA END AND
		(MONTH(FECHARES) = @MES OR @MES is null) AND
		YEAR(FechaRes)=@ANIO 
	GROUP BY USUARIO
	ORDER BY 2 DESC
	
	SET NOCOUNT OFF
END
GO

IF OBJECT_ID (N'[S_View_TicketsConSLA_Top10UsuarioDetalle]', N'P') IS NOT NULL
	DROP PROCEDURE [S_View_TicketsConSLA_Top10UsuarioDetalle]
GO

CREATE PROCEDURE [S_View_TicketsConSLA_Top10UsuarioDetalle]
	@TIPO NVARCHAR(510),
	@GRUPO NVARCHAR(510),
	@AREA NVARCHAR(510),
	@ANIO INT,
	@MES INT
AS
BEGIN
	SET NOCOUNT ON
	SET DATEFORMAT DMY

	DECLARE @TOPTEN TABLE
	(	USUARIO NVARCHAR(201),
		TICKETS INT
		)

	INSERT INTO @TOPTEN
	EXECUTE [S_View_TicketsConSLA_Top10Usuario] @TIPO, @GRUPO, @AREA, @ANIO, @MES

	SELECT	UPPER(LTRIM(RTRIM(USUARIO))) AS USUARIO,
			DESCCAT AS CATEGORIA,
			COUNT(TICKET) AS CANTIDAD
	FROM VIEW_TICKETSCONSLA WITH(NOLOCK)
	WHERE
		[TIPO] = CASE WHEN LEN(LTRIM(RTRIM(@TIPO)))=0 THEN [TIPO] ELSE @TIPO END AND
		[GRUPO] = CASE WHEN LEN(LTRIM(RTRIM(@GRUPO)))=0 THEN [GRUPO] ELSE @GRUPO END AND
		ISNULL([ÁREA DE USUARIO],'') = CASE WHEN LEN(LTRIM(RTRIM(@AREA)))=0 THEN ISNULL([ÁREA DE USUARIO],'') ELSE @AREA END AND
		(MONTH(FECHARES) = @MES OR @MES is null) AND
		YEAR(FechaRes)=@ANIO AND
		USUARIO IN	(SELECT DISTINCT USUARIO FROM @TOPTEN)
	GROUP BY USUARIO, DESCCAT
	ORDER BY 1, 3 DESC
	
	SET NOCOUNT OFF
END
GO

IF OBJECT_ID (N'[S_View_TicketsConSLA_Top10Area]', N'P') IS NOT NULL
	DROP PROCEDURE [S_View_TicketsConSLA_Top10Area]
GO

CREATE PROCEDURE [S_View_TicketsConSLA_Top10Area]
	@TIPO NVARCHAR(510),
	@GRUPO NVARCHAR(510),
	@AREA NVARCHAR(510),
	@ANIO INT,
	@MES INT
AS
BEGIN
	SET NOCOUNT ON
	SET DATEFORMAT DMY

	SELECT	TOP 10 UPPER(LTRIM(RTRIM(ISNULL([ÁREA DE USUARIO],'USUARIO SIN ÁREA ASIGNADA')))) AS AREA,
			COUNT(TICKET) AS CANTIDAD
	FROM VIEW_TICKETSCONSLA WITH(NOLOCK)
	WHERE
		[TIPO] = CASE WHEN LEN(LTRIM(RTRIM(@TIPO)))=0 THEN [TIPO] ELSE @TIPO END AND
		[GRUPO] = CASE WHEN LEN(LTRIM(RTRIM(@GRUPO)))=0 THEN [GRUPO] ELSE @GRUPO END AND
		ISNULL([ÁREA DE USUARIO],'') = CASE WHEN LEN(LTRIM(RTRIM(@AREA)))=0 THEN ISNULL([ÁREA DE USUARIO],'') ELSE @AREA END AND
		(MONTH(FECHARES) = @MES OR @MES is null) AND
		YEAR(FechaRes)=@ANIO 
	GROUP BY [ÁREA DE USUARIO]
	ORDER BY 2 DESC
	
	SET NOCOUNT OFF
END
GO

IF OBJECT_ID (N'[S_View_TicketsConSLA_Top10AreaDetalle]', N'P') IS NOT NULL
	DROP PROCEDURE [S_View_TicketsConSLA_Top10AreaDetalle]
GO

CREATE PROCEDURE [S_View_TicketsConSLA_Top10AreaDetalle]
	@TIPO NVARCHAR(510),
	@GRUPO NVARCHAR(510),
	@AREA NVARCHAR(510),
	@ANIO INT,
	@MES INT
AS
BEGIN
	SET NOCOUNT ON
	SET DATEFORMAT DMY

	DECLARE @TOPTEN TABLE
	(	AREA NVARCHAR(201),
		TICKETS INT
		)

	INSERT INTO @TOPTEN
	EXECUTE [S_View_TicketsConSLA_Top10Area] @TIPO, @GRUPO, @AREA, @ANIO, @MES

	SELECT	UPPER(LTRIM(RTRIM(ISNULL([ÁREA DE USUARIO],'USUARIO SIN ÁREA ASIGNADA')))) AS AREA,
			DESCCAT AS CATEGORIA,
			COUNT(TICKET) AS CANTIDAD
	FROM VIEW_TICKETSCONSLA WITH(NOLOCK)
	WHERE
		[TIPO] = CASE WHEN LEN(LTRIM(RTRIM(@TIPO)))=0 THEN [TIPO] ELSE @TIPO END AND
		[GRUPO] = CASE WHEN LEN(LTRIM(RTRIM(@GRUPO)))=0 THEN [GRUPO] ELSE @GRUPO END AND
		ISNULL([ÁREA DE USUARIO],'') = CASE WHEN LEN(LTRIM(RTRIM(@AREA)))=0 THEN ISNULL([ÁREA DE USUARIO],'') ELSE @AREA END AND
		(MONTH(FECHARES) = @MES OR @MES is null) AND
		YEAR(FechaRes)=@ANIO and
		ISNULL([ÁREA DE USUARIO],'USUARIO SIN ÁREA ASIGNADA') IN (SELECT DISTINCT AREA FROM @TOPTEN)
	GROUP BY [ÁREA DE USUARIO], DESCCAT
	ORDER BY 1, 3 DESC
	
	SET NOCOUNT OFF
END
GO

IF OBJECT_ID (N'[S_View_TicketsConSLA_Top10Categoria]', N'P') IS NOT NULL
	DROP PROCEDURE [S_View_TicketsConSLA_Top10Categoria]
GO

CREATE PROCEDURE [S_View_TicketsConSLA_Top10Categoria]
	@TIPO NVARCHAR(510),
	@GRUPO NVARCHAR(510),
	@AREA NVARCHAR(510),
	@ANIO INT,
	@MES INT
AS
BEGIN
	SET NOCOUNT ON
	SET DATEFORMAT DMY

	SELECT	TOP 10 UPPER(LTRIM(RTRIM(DESCCAT))) AS CATEGORIA,
			COUNT(TICKET) AS CANTIDAD
	FROM VIEW_TICKETSCONSLA WITH(NOLOCK)
	WHERE
		[TIPO] = (CASE WHEN LEN(LTRIM(RTRIM(@TIPO)))=0 THEN [TIPO] ELSE @TIPO END) AND
		[GRUPO] = (CASE WHEN LEN(LTRIM(RTRIM(@GRUPO)))=0 THEN [GRUPO] ELSE @GRUPO END) AND
		ISNULL([ÁREA DE USUARIO],'') = (CASE WHEN LEN(LTRIM(RTRIM(@AREA)))=0 THEN ISNULL([ÁREA DE USUARIO],'') ELSE @AREA END) AND
		(MONTH(FECHARES) = @MES OR @MES is null) AND
		YEAR(FechaRes)=@ANIO
	GROUP BY DESCCAT
	ORDER BY 2 DESC
	
	SET NOCOUNT OFF
END
GO
--[S_View_TicketsConSLA_Top10Usuario] '','','','01/01/2010','12/31/2010'
--GO
--[S_View_TicketsConSLA_Top10Area] '','','','01/01/2010','12/31/2010'
--GO
--[S_View_TicketsConSLA_Top10Categoria] '','','','01/01/2010','12/31/2010'
