USE Tablero
GO
IF OBJECT_ID (N'[S_View_TicketsPorEstados_AnalisisCategoria]', N'P') IS NOT NULL
	DROP PROCEDURE [S_View_TicketsPorEstados_AnalisisCategoria]

GO
CREATE PROCEDURE [S_View_TicketsPorEstados_AnalisisCategoria]
	@TIPO NVARCHAR(510),
	@GRUPO NVARCHAR(510),
	@AREA NVARCHAR(510),
	@FECHA_INI DATETIME,
	@FECHA_FIN DATETIME
AS
BEGIN
	SET NOCOUNT ON

	SELECT	YEAR(TPE.FECHAAPE) AS ANIO,
			MONTH(TPE.FECHAAPE) AS CODMES,
			EQU.CATEGORIAREPORTE,
			COUNT(TICKET) AS CANTIDAD
	FROM View_TicketsPorEstados TPE WITH(NOLOCK)
	INNER JOIN Categoria_Equilavencia EQU WITH(NOLOCK) ON 		
			CASE WHEN CHARINDEX('.',TPE.CATEGORÍA) = 0
				THEN 'XX'
				ELSE SUBSTRING(TPE.CATEGORÍA,1,CHARINDEX('.',TPE.CATEGORÍA)-1)
			END = EQU.CATEGORIA
	WHERE
		TPE.[TIPO] = CASE WHEN LEN(LTRIM(RTRIM(@TIPO)))=0 THEN TPE.[TIPO] ELSE @TIPO END AND
		TPE.[GRUPO] = CASE WHEN LEN(LTRIM(RTRIM(@GRUPO)))=0 THEN TPE.[GRUPO] ELSE @GRUPO END AND
		ISNULL(TPE.[ÁREA DE USUARIO],'') = CASE WHEN LEN(LTRIM(RTRIM(@AREA)))=0 THEN ISNULL(TPE.[ÁREA DE USUARIO],'') ELSE @AREA END AND
		TPE.[FECHAAPE] BETWEEN @FECHA_INI AND @FECHA_FIN --AND
		--EQU.CATEGORIAREPORTE NOT IN ('Google','INC','REQ','Sin Categoria','Desarrollo')
	GROUP BY YEAR(TPE.FECHAAPE), MONTH(TPE.FECHAAPE), EQU.CATEGORIAREPORTE
	ORDER BY YEAR(TPE.FECHAAPE), MONTH(TPE.FECHAAPE)

	SET NOCOUNT OFF
END
GO
--[S_View_TicketsPorEstados_AnalisisCategoria] '','','','01/01/2009','01/12/2011'



